### ISSUE TITLE
アプリ再起動時にクラッシュする可能性がある

### ISSUE THREAD

**Issue by suzukiplan** [suzukiplan/tohovgs4-android#23]
Firebaseからver4.13で安定性に関する問題のレポートがあったので調査する。

SongListFragment から MainActivity の musicManager へアクセスした際に未初期化状態のためクラッシュしているので、現象としては「起動時にクラッシュする」というものだと思われる。

```
Fatal Exception: a8.g: lateinit property musicManager has not been initialized
       at com.suzukiplan.tohovgs.MainActivity.getMusicManager(MainActivity.java:7)
       at com.suzukiplan.tohovgs.SongListFragment.onCreateView(SongListFragment.java:5)
       at androidx.fragment.app.Fragment.S(Fragment.java:19)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:4)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:8)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:1)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1)
       ~~~ 以下略 ~~~
```

推定原因: MusicManagerの初期化を非同期化したことでレースコンディションするようになったシーケンスがある可能性があるものと考えられる。

**Comment by suzukiplan** [comment]
見直したがレースコンディションは一見すると無さそう。
よくよく見ると `FragmentStateManager` 経由で SongListFragmentが 再生成されていることが分かる。
つまり、純粋なプロセス起動時には問題が起きなくて、プロセスが終了せずにActivityが再生成された時の savedBundleState からの復帰した時に問題が起きているっぽい。

1. アプリ起動
2. 戻るボタンで終了
3. アプリ起動
4. 戻るボタンで終了
　：

を延々と繰り返せば再現できるかもしれないので、確認してみる。

**Comment by suzukiplan** [comment]
再現しないなぁ...

多分、アプリ終了時にMainActivityのメイン画面コンテナからremoveAllFragmentsしてあげれば、savedBundleStateにFragmentの状態が記録されなくなることで、再起動時の意図しない再生性を抑止できるのではないかと考えられるので、修正自体は簡単そうだけど。

**Comment by suzukiplan** [comment]
スタックトレースより少なくとも初回起動時は問題ない（プロセスが落ちた後の再起動では問題なく起動できている）と考えられるので、改題。

**Comment by suzukiplan** [comment]
corrected in https://github.com/suzukiplan/tohovgs4-android/pull/24/commits/14bd259b37606a8f4792b1d774746dea7bd10c3d

**Comment by suzukiplan** [comment]
ver4.14で同件の発生レポートを1件確認したので再オープンします。

```
Fatal Exception: a8.g: lateinit property musicManager has not been initialized
       at com.suzukiplan.tohovgs.MainActivity.getMusicManager(MainActivity.java:7)
       at com.suzukiplan.tohovgs.SongListFragment.onCreateView(SongListFragment.java:5)
       at androidx.fragment.app.Fragment.S(Fragment.java:19)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:4)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:8)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:1)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:4)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:4)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8173)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3606)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8040)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```
