### ISSUE TITLE
Android 9 で movePage した時にクラッシュ

### ISSUE THREAD

**Issue by suzukiplan** [suzukiplan/tohovgs4-android#25]
Firebase Crashlytics のレポートで確認:

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:4)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
       at com.suzukiplan.tohovgs.MainActivity.movePage(MainActivity.java:23)
       at com.suzukiplan.tohovgs.MainActivity.movePage(MainActivity.java:11)
       at com.suzukiplan.tohovgs.MainActivity$onCreate$5$1.invoke$lambda-0(MainActivity.java:11)
       at com.suzukiplan.tohovgs.MainActivity$onCreate$5$1$$InternalSyntheticLambda$2$02d8c901746bb102c08cd723bba8eff8b370a9c50c612831dece210f01f07c4d$0.run(MainActivity.java:11)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6746)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Android 9 でしか起きていないらしい & 9 の実機が手元にないので、エミュレータで動作検証して対策を検討する。

**Comment by suzukiplan** [comment]
AVDでAndroid9の環境構築してテストしたけど発生せず。

_また、savedBundleState関連かなと思ったけど、`MainActivity#onCreate` での `movePage` で発生しているので、単純に起動するだけで落ちる筈だが。_

**Comment by suzukiplan** [comment]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```

https://qiita.com/nein37/items/32613e9acd9558566c5e

なるほど

**Comment by suzukiplan** [comment]
https://github.com/suzukiplan/tohovgs4-android/pull/24/commits/065a5591094ea56046b4744c8784717cebc1b41e にて対策済み
